#!/usr/bin/env bash
# SPDX-FileCopyrightText: The jsonnet-oci-images Authors
# SPDX-License-Identifier: 0BSD
#
# Generate LIBRARIES.md from libraries.json (or $1). The discovery workflow runs
# this after refreshing the manifest, so the published-image list is never
# hand-maintained. REGISTRY overrides the image namespace (e.g. ghcr.io/metio).
set -euo pipefail
manifest="${1:-libraries.json}"
registry="${REGISTRY:-ghcr.io/metio}"

cat <<EOF
<!--
SPDX-FileCopyrightText: The jsonnet-oci-images Authors
SPDX-License-Identifier: 0BSD
-->
<!-- GENERATED by hack/gen-readme.sh from libraries.json — do not edit by hand. -->

# Published images

$(jq -r 'length' "$manifest") libraries, each at \`:latest\` (all upstream versions inside;
pick one in the import path). Multi-version libraries also carry a synthesized
\`latest\` alias.

| Library | Image | Upstream |
|---|---|---|
EOF
jq -r --arg reg "$registry" \
  '.[] | "| \(.name) | `\($reg)/joi-\(.org)-\(.repo)` | [\(.org)/\(.repo)](\(.source)) |"' \
  "$manifest" | sort
